# Generated by Django 4.2 on 2024-06-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='Превью курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('price', models.PositiveIntegerField(default=10000, verbose_name='стоимость курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Превью урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studing.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'подписка на обновление',
                'verbose_name_plural': 'подписки на обновления',
            },
        ),
    ]
